gpu-mode/discord-cluster-manager

.github/workflows/train_workflow.yml
The original issue for installs was that train.py didn't exist in the workflow yet.
=> Re-order write to train.py and install accordingly

.github/workflows/train_workflow.yml
This change adds train.py to the artifacts that are uploaded to GitHub actions. Previously just training.log was uploaded.
=> Upload train.py in train_workflow.yml

tests/discord-bot-smoke-test.py
Siro noticed that the smoke test was always grabbing the Discord token and didn't have an option to grab the Discord debug token. This change gives the smoke test a `--debug` option which, if set, grabs the debug token. This makes the smoke test act in the same way as the bot when the debug option is given on the command line.
```bash
```
- Start a training run by with the slash command `/run`.
You may need to exercise some judgement about the script and GPU type.
- Wait for the training run to complete.
- Copy the URL for the thread started by the cluster bot in response to
your `/run` message ("Cluster Bot started a thread: ..."):
- Click on the 3 dots …
=> add debug option to smoke test

scripts/modal-test.py, src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/modal_runner.py
This PR adds telemetry logs for the following metrics:
* File size
* How long a given job took to get queued
* How long to execute/run
**Screenshots:**
| ![Screenshot 1](https://github.com/user-attachments/assets/2442c354-1ccf-48c6-916c-99e86c1689b1) | ![Screenshot 2](https://github.com/user-attachments/assets/0b0a2c02-7270-4495-b614-f225c6e5601d) |
| --- | --- |
> [!NOTE]
> For Modal, it is [not possible](https://modallabscommunity.slack.com/archives/C069RAH7X4M/p1732770908880519) to programmatically fetch cold start time vs. execution time. 
Assuming our GPUs are warmed up prior to competition then cold start time should not pollute manual calculations of execution time which is good if we want to use that as our ranking function.
As for GitHub Actions, I think I need direct access to …
=> More informative execution logs/telemetry

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py
Adds a `/verifyrun` command that does the same work as the smoke test but is easier to use.
```bash
```
- Start a training run by with the slash command `/run`.
You may need to exercise some judgement about the script and GPU type.
- Wait for the training run to complete.
- Copy the URL for the thread started by the cluster bot in response to
your `/run` message ("Cluster Bot started a thread: ..."):
- Click on the 3 dots (`...`) to the cluster bot's message.
- Select *Copy Message Link*.
- Using the copied URL, run the smoke test:
```bash
python discord-bot-smoke-test.py copied_url
```
- Verify that the smoke test script responds with:
```
All tests …
```
=> add /verifyruns cog

.github/workflows/amd_workflow.yml, .github/workflows/nvidia_workflow.yml, .gitignore, src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/consts.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/leaderboard_eval.py, src/discord-cluster-manager/utils.py
Enable the creation of leaderboards with a reference script. Currently, the creator has control over all aspects of the script, and only must define a function `def metric() -> float` that returns a score (e.g. wall-clock time). The current flow is
1. Create a leaderboard, e.g. `/leaderboard create {kernel_name} {deadline} {reference.py}
2. Submit a train script with a pre-defined name. This is based on what reference.py expects. e.g. `/leaderboard submit {github/modal} {GPU_TYPE} {script.py}. Wait until the runners are done (takes ~1-2 min atm).
3. See your placement. `/leaderboard show {kernel_name}
The way we grab the score / speed from the eval script and save to the DB is really hacky. I basically look at the saved logs and look for a specific parsable string. We definitely want to …
=> Add GitHub (NVIDIA / AMD) Runners to /leaderboard submit and allow Leaderboard Submissions

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/utils.py
Note, this change requires the bot to have `Server Members Intent` turned on.
The previous leaderboard doesn't show usernames -- it instead shows the user ID numbers, which are not useful. We instead now just grab the user names / nicks (nicks take precedence) using the user IDs. Note that the DB is unchanged and still uses user IDs as keys.
```bash
```
- Start a training run by with the slash command `/run`.
You may need to exercise some judgement about the script and GPU type.
- Wait for the training run to complete.
- Copy the URL for the thread started by the cluster bot in response to
your `/run` message ("Cluster Bot started a thread: ..."):
- Click …
=> Grab and show user names and nicks instead of User IDs

src/discord-cluster-manager/cogs/leaderboard_cog.py
Calling `/leaderboard submit github` with an unknown leaderboard name results in a traceback and no response on the Discord channel.
```
024-12-12 17:48:37 ERROR    discord.app_commands.tree Ignoring exception in command 'github'
Traceback (most recent call last):
File "/home/.../Code/Discord-cluster-manager/.venv/lib/python3.13/site-packages/discord/app_commands/commands.py", line 857, in _do_call
return await self._callback(self.binding, interaction, **params)  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/.../Code/Discord-cluster-manager/src/discord-cluster-manager/cogs/leaderboard_cog.py", line 129, in submit_github
await interaction.response.send_message(
f"Leaderboard {leaderboard_name} not found.", ephemeral=True
)
File …
```
=> switch to interaction.followup.send in some places in leaderboard cog

src/discord-cluster-manager/cogs/leaderboard_cog.py
siro requested a change in leaderboard_cog.py where to use `interaction.response.send_message` for initial validations and thereafter use `interaction.followup.send`.
I noticed a problem where the submission content was not being decoded. As a result, we get rows in the submission table like this (note the binary-looking data in the `code` column):
```
clusterdev=# select * from leaderboard.submission where id=8;
-[ RECORD 1 ]---
id              | 8
problem_id      | 1
name            | train.py
user_id         | 704502776683692072
code            | \x696d706f727420746f7263680a0a64656620637573746f6d5f736f66746d617828783a20746f7263682e54656e736f722c2064696d3a20696e74203d202d3129202d3e20746f7263682e54656e736f723a0a2020202072657475726e20746f7263682e6e6e2e66756e6374696f6e616c2e736f66746d617828 …
```
=> fixes for a couple of things in leaderboard cog

src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/migrations/20241214_01_M62BX-drop-old-leaderboard-tables.py
This PR drops leaderboard tables in the public schema that we're no longer using.
I kind of did the following: I ran Modal and GitHub runs and visually inspected their output. `\verifyruns` is still broken because it does not have `score:` lines in the output.
```bash
```
```
```
README.md.
=> drop old leaderboard tables

.github/workflows/amd_workflow.yml, .github/workflows/nvidia_workflow.yml
Remove the scores step in the NVIDIA and AMD job submission workflows.
```bash
```
```
```
README.md.
=> Remove "score regex" to fix /verifyruns

src/discord-cluster-manager/cogs/leaderboard_cog.py
Add a Discord `ui.View` dropdown with a list of GPUs. Currently, the list of GPUs is independent of the runner, but this is subject to change in a later PR.
```bash
```
```
```
README.md.
=> Add dropdown UI for leaderboard creation.

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/utils.py
This PR refactors the try-except logic in the leaderboard cog. It also removes redundant prints, and prevents leaking exact error traces to the Discord user. It also fixes a bug for when a duplicate leaderboard is created, and returns a better user message.
```bash
```
```
```
README.md.
=> Refactoring try-excepts and remove prints.

src/discord-cluster-manager/cogs/leaderboard_cog.py
A one-line change to change `/leaderboard get` to `/leaderboard list`, which makes a lot more sense for listing available leaderboards.
```bash
```
```
```
README.md.
=> Change: /leaderboard get --> /leaderboard list

src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/misc_cog.py, src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/utils.py
To avoid issues where Discord complains about the correct usage of send / followup, we add a wrapper that checks which is valid, and uses the correct command. This feature is important for callbacks, where an existing response might exist, despite the GitHub slash command function assuming it does not.
```bash
```
```
```
For more information on running a cluster bot on your …
=> Replace all relevant Interaction.send/followups with send_discord_message wrapper

.github/workflows/nvidia_workflow.yml, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_eval.py
The old leaderboard submission eval code expects a `metric()` function from the reference code specified by the leaderboard creator. Instead, we only expect the leaderboard creator to have 2 functions: the reference kernel itself, and an input data generator. We now handle checking implementations and runtimes on our end to avoid hacking and to allow us to quickly fix leaderboard issues. This change was per last Tuesday's meeting.
We will probably update `leaderboard_eval.py` over time, this is just a simple implementation to start that is usable for Python / Triton.
Example of what new reference code may look like for softmax:
```
import torch
from typing import List
def ref_kernel(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
"""
Reference implementation of the Softmax function using …
```
=> Refactor Leaderboard Submission Eval Code.

src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/migrations/20241221_01_54Oeg-rename-problem-table.py
The table for storing data about leaderboard challenges was named `problem`. This didn't seem like a good name, and @alexzhang13 expressed a preference for the name `leaderboard`.
```bash
```
```
```
README.md.
=> rename problem table to leaderboard

src/discord-cluster-manager/cogs/leaderboard_cog.py
This change removes a bit of extra text that gets displayed in the `/leaderboard list` output.
Before this change:
After this change:
```bash
```
```
```
README.md.
=> stop sending interaction in leaderboard list

src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/migrations/20241222_01_ELxU5-add-gpu-types.py
This PR adds a table to the leaderboard schema to track the GPU types for each leaderboard. It also adds a column to the runinfo table to track the GPU type that the run used.
After creating a leaderboard named `gpu_types` using `/leaderboard create`:
```
clusterdev=# select name, id from leaderboard.leaderboard;
name     | id 
--------------+----
softmax_test |  1
gpu_types    |  3
(2 rows)
clusterdev=# select * from leaderboard.gpu_type where leaderboard_id = 3;
leaderboard_id | gpu_type 
----------------+----------
3 | NVIDIA
3 | AMD
(2 rows)
```
```bash
```
- Verify that the bot eventually …
=> adds table and column to track gpu types

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py
`/leaderboard list` now shows the name, deadline, and associated GPU types all linted properly. Eventually, we'll want to **move a lot of the rendering code to another function and clean up constants to const.py**, but this is a first working version.
```bash
```
```
```
README.md.
=> `/leaderboard list` now shows all leaderboards with associated GPU types

src/discord-cluster-manager/migrations/20241224_01_Pg4FX-delete-cascade.py
This PR changes foreign key constraints to 'on delete cascade'.
```bash
```
```
```
README.md.
=> changed foreign keys to 'on delete cascade'

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/utils.py
This PR adds functionality for submitting to a leaderboard with certain GPUs, and showing the results (these go hand-in-hand currently, so I didn't separate the PRs).
As an example:
```bash
```
```
```
README.md.
=> Add support for submitting to specific GPUs per leaderboard and show

src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py
Super simple change to make sure all the reference code / eval code doesn't complain when a user submits a file not named "train.py".
```bash
```
```
```
README.md.
=> Allow user submissions to have arbitrary names

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/utils.py
We forcibly delete the selection UI so it's not visible to other users. This removes clutter on the Discord chat, and also prevents other users from interacting with a useless UI.
Old:
Example:
```bash
```
```
```
README.md.
=> Remove GPU Selection UI on slash commands.

README.md
Add reference kernel function signatures for CUDA, also update Python reference kernel function signatures.
```bash
```
```
```
README.md.
=> Update README with new reference script expectations for Python / CUDA.

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py
Logic for preventing submissions to a leaderboard once the deadline has passed (by date). We may later need to implement something for timezones and all, but I think for now as long as the Discord bot sits on the same server this doesn't really matter.
```bash
```
```
```
README.md.
=> Prevent submitting when date is past deadline.

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/consts.py, src/discord-cluster-manager/modal_runner.py, src/discord-cluster-manager/modal_runner_archs.py
This is a relatively large PR with a lot of finishing changes for modal support and ThunderKittens (TK) support.
Namely,
1. We can compile (only tested on just importing and building) ThunderKittens kernel on Modal. More extensive testing coming.
2. The UI for Modal actually works now, and the GPUs you submit to are correct. You can now submit to whatever GPUs you want. You can also submit to more than just the T4s now.
3. A big re-factor to greatly simplify Modal runner code, and merge most of the GitHub runner logic to also work with Modal. The GH/Modal runner logic is now <30 lines.
4. We currently add clone TK when setting up the Modal image, but we may want to do this differently. Happy to make changes in the future.
5. The Modal runners run the Modal Cog, similar to the GitHub …
=> Finish up Modal support + Example of ThunderKittens working

k8s/README.md
- Provide docs on establishing a Kubernetes-hosted GitHub Actions Runner/Runner Scale Set with GPU enablement
```bash
```
```
```
README.md.
=> Add documentation for configuring GHA Runner Scale Sets

README.md, examples/vectoradd_cuda_inline/reference.py, examples/vectoradd_cuda_inline/submission.py, examples/vectoradd_triton/reference.py, examples/vectoradd_triton/submission.py
Implemented two sample of vectors add:
- Pytorch CUDA online 
- Triton
- [ X] Run the slash command `/verifyruns` on your own server.
```bash
```
```
```
README.md.
=> Vectors Add - Pytorch CUDA inline and Triton example

src/discord-cluster-manager/cogs/leaderboard_cog.py
Enables creating a leaderboard with the same name after deleting the old one. Issue was caused by the forum channel already existing. Therefore we solve this by renaming the original thread to {original_name} - archived at {timestamp} to avoid having 2 same names.
```bash
```
```
```
README.md.
=> Fix: enable creation of a lb with the same name after deleting the old one

src/discord-cluster-manager/eval.cu, src/discord-cluster-manager/leaderboard_eval.py
This change in itself isn't super useful, but I want this to be a separate PR because we have squashing enabled, and this should be its own commit which is purely copying the string contents into the new file, so we can do proper change tracking going forth.
=> move eval into its own file for easier development

src/discord-cluster-manager/modal_runner_archs.py
Small fix that just fixes typos in the modal runners, calling the correct runners based on file type. @ngc92 
```bash
```
```
```
README.md.
=> Fix: wrong function calls to modal runners

examples/identity_cuda/reference.cuh, examples/identity_py/reference.py, src/discord-cluster-manager/eval.cu, src/discord-cluster-manager/eval.py, src/discord-cluster-manager/run_eval.py
adds a seed argument to data generation functions.
**NOTE**  This requires an update to existing leaderboard reference files
Here, I've only updated the identity test so far.
=> generate_input receives a random seed argument

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/leaderboard_cog.py
Add a channel that just displays the leaderboard. Had to also split up cog functionality from forming the leaderboard to get this to work (you can't just call slash commands internally).
The read-only channel looks like so: It just repeatedly edits the same message (or adds an initial one) with an updated LB.
```bash
```
```
```
For more information on running a cluster bot …
=> Add a persistent Leaderboard Channel

src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/github_runner.py
refactors the github runner:
Most of the non-discord specific functionality is separated out into a helper, keeping only the actually discord-relevant bits inside the cog.
~~When testing, I also found that submitting a single script "run github" command was broken, because we unconditionally used to set eval.py, so there is also a drive-by fix here.~~ [went away when rebasing]
It also tried to be closer to the modal cog, in that instead of spamming messages, we update one message as we're waiting for the run to finish.
when testing this locally, I get warnings like
> 2025-01-18 03:37:58 WARNING  discord.gateway Shard ID None heartbeat blocked for more than 10 seconds.
not completely sure what this means, I guess  it's blocking in a code path that shouldn't be?
=> GitHub refactor

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/misc_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/github_runner.py
When logging with `logger.error`, we want to include the exception info, so that the cause can be identified in the traceback.
also found two missing `await` statements.
This is based on top of #137
=> small fixes of problems encoutered during development

src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/consts.py, src/discord-cluster-manager/report.py
On top of #138
Joins github and modal cogs together with a  common base class that implements most of the functionality.
in doing so, also splits running  to `run` command dedicated to individual scripts (no eval, no reference) and leaderboard submissions (currently reference code; in the future, a generic config object)
=> Yet more refactoring

src/discord-cluster-manager/report.py
as the title says, and a bugfix I thought was already in an earlier PR
=> split generate_report into smaller functions

scripts/ci_test_cuda.py, scripts/ci_test_python.py, src/discord-cluster-manager/run_eval.py
cap output returned by our runs to 16K for stderr and stdout; add tests verifying the limit
=> limit stdout and stderr capture to 16KiB

src/discord-cluster-manager/cogs/leaderboard_cog.py
Description
Small fix, PR #144 introduced a subtle bug that if only 1 gpu was available, it would not call gpu_view, resulting in the interaction defer not being called. As only 1 command calls this view, I moved the defer into the command as it's not view specific.
```bash
```
```
```
README.md.
=> Fix: application timeout in fast-track if only 1 gpu

scripts/ci_test_cuda.py, scripts/ci_test_python.py, src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/consts.py, src/discord-cluster-manager/run_eval.py, src/discord-cluster-manager/utils.py
* Adds additional arguments for cuda compiles that allow specifying link libraries, defines, and generic flags.
* Additional verification and unit tests.
The additional checks that supplied include directories actually exist required to move the modal-specific thunderkittens include into the modal cog.
=> Make run_cuda_script accept more compile flags arguments

.github/workflows/amd_workflow.yml, src/discord-cluster-manager/cogs/github_cog.py
This commit adds mi300 nodes as an option to the current amd workflow.
I tested a couple times on the AMD workflow here (https://github.com/gpu-mode/discord-cluster-manager/actions/runs/12902691574)
```bash
```
```
```
README.md.
=> Add MI300X Runners to AMD workflow.

requirements.txt
Small pr to fix deploy to heroku (forgot to add reqs in #143)
```bash
```
```
```
README.md.
=> Fix: add requirements

.github/workflows/runner.py, scripts/ci_test_cuda.py, scripts/ci_test_python.py, src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/modal_runner.py, src/discord-cluster-manager/report.py, src/discord-cluster-manager/run_eval.py, src/discord-cluster-manager/task.py
Update evalulation runs:
* Attach a potential compile result to _each_ run (we might want to compile tests without `-DNDEBUG`, for example; not part of this PR, though)
* record start and end time of runs
* have task specific timeouts for test, benchmark, and ranked runs, with reasonable defaults (i hope; maybe they should be even lower?)
* restructuring of eval code
Testing these changes requires making a deploy to modal so the new test script is there.
=> Update of result structures and eval runs

src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/migrations/20250221_01_GA8ro-submission-collection.py, src/discord-cluster-manager/utils.py
This is a first attempt at reworking our database to enable detailed recording of submissions.
It split submissions into 3 tables:
1) code files. Here we store the actually submitted code. We have a hash column that allows us to quickly detect if the same code is submitted again, and in this case we just don't add it (e.g., multiple commands run with the same code, e.g., multiple benchmarks or multiple runs explicitly specifying different GPUs, or everyone testing our example script :)), no need to spam our DB with redundant data.
2) A table for an individual "submission", that is, one invocation of a bot command. This is associated with a code, and adds information about submission time, leaderboard and user. We also record a filename, and have a special flag "done" that starts out false …
=> Database update to record submissions

Aptfile, src/discord-cluster-manager/cogs/admin_cog.py
Fixes Update Lb command
TODO: support different upstreams?
```bash
```
```
```
README.md.
=> Fix: fix update leaderboards

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/misc_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/ui/misc.py, src/discord-cluster-manager/utils.py
some logging improvements
created a dedicated Exception subclass that we can use to communicate error messages across call boundaries. We don't want to use  the original exceptions, because we cannot actually display them to the user as we just don't know what kind of info might be visible in the exception object. For `KernelBotError`, the idea is that this indicates that the message of the exception object is intended specifically to be displayed to the user.
This avoids some cases where our db functions return strings only for the purpose of allowing error handling, and makes it harder to accidentally ignore such errors.
Additionally, contains some clean-up fixes, such as moving `resync` to the `admin` commands.
=> error handling and logging

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/env.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/report.py, src/discord-cluster-manager/ui/misc.py
A bunch of small fixes, and some improvements to smoothen the dev process (hopefully):
* A new verify-task command, that gets a task directory, creates a temporary leaderboard, submits test, benchmark, and ranked runs, then cleans up the LB again.
* delete_leaderboard has a `force` parameter that will delete all submissions to that leaderboard. That should **only** be used for dummy leaderboards, in other cases we want to preserve existing submissions.
* ability  to select base folder for problem development (defaults to `examples`)
=> Fixes and dev improvements

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/utils.py
Updates to `verify-task` : 
* can decide to run only test/benchmark/ranked or all
* looks for things to run in `solutions/{correct,wrong}` subfolders
* automatically verifies that `correct`  solutions get `passed`  status, and `wrong` solutions don't
=> better verify

src/discord-cluster-manager/cogs/misc_cog.py
Basically allows retrieving the api-url only if not debug mode, else sends a message that it's coming soon.
```bash
```
```
```
README.md.
=> Feat: hide api url for now

src/discord-cluster-manager/run_eval.py
Provides a compilation run to python solutions for inline Cuda. 
```bash
```
```
```
README.md.
=> Fix: timeout issues

src/discord-cluster-manager/modal_runner_archs.py
The `app.function` parameter `gpu` will map work onto more than one GPU type when provided the strings `"A100"` and `"H100"`, which makes benchmarking noisier.
This PR changes those strings to `"A100-80GB"` and `"H100!"` (`!` meaning "strict") so that work is mapped onto only one GPU type.
```bash
```
```
```
For more information on running a cluster bot on your own server, …
=> stricter gpu scheduling for a100s and h100s

.gitignore, requirements.txt, scripts/ci_test_python.py, src/discord-cluster-manager/consts.py, src/discord-cluster-manager/run_eval.py
```bash
```
```
```
README.md.
=> Double timeouts

.github/workflows/amd_workflow.yml, .github/workflows/publish_amd_docker.yml, docker/amd-docker.Dockerfile
This commit adds a docker that is used as the base for the mi300 runners. This is to help with cold start times (including torch rocm now) and provide a centralized source of truth that is published daily and automatically picked up by mi300 runners every time there is a publish
```bash
```
```
``` …
=> Add amd docker and daily publisher.

src/discord-cluster-manager/github_runner.py
```bash
```
```
```
README.md.
=> Fix: lower the polling timeout

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/report.py
Create _private_ threads for detailed submission info, link to them in an ephemeral summary message that tracks the status of the entire submission.
+some additional refactoring
This is currently deployed on dev, so you can test it on the staging bot.
=> Improvements to submission UI

src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/migrations/20250316_01_5oMi3-remember-forum-id.py, src/discord-cluster-manager/utils.py
This PR keeps track of the id of the forum thread associated with a leaderboard.
In itself, this isn't very useful yet, but in the future, it lets us communicate more easily in a leaderboard-specific channel.
=> Keeping track of forum thread

examples/eval.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/migrations/20250329_01_7VjJJ-add-a-secret-seed-column.py, src/discord-cluster-manager/run_eval.py, src/discord-cluster-manager/task.py, src/discord-cluster-manager/utils.py
Enable (and use) secret seeds in the default python runner (`examples/eval.py`).
Secret seeds are not used in `eval.cu` yet.
Requires a modal redeploy.
Because `eval.py` is baked into the task definitions, none of the existing tasks will benefit from this. We'll need to figure out how to update existing tasks separately.
=> Enable secret seeds

src/discord-cluster-manager/api/main.py, src/discord-cluster-manager/env.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/migrations/20241226_01_ZQSOK-add_gpu_type_to_submission.py, src/discord-cluster-manager/migrations/20250221_01_GA8ro-submission-collection.py, src/discord-cluster-manager/migrations/20250403_01_CSfnQ-user-info-add-cli-id.py, src/discord-cluster-manager/migrations/20250406_01_ZXjWK-user-info-add-cli-id.py
Enables authentication via discord oauth -> we set redirect url to our `/auth/cli` (we figure out a proper name later), each cli instance gets a unique `cli_id` generated which maps user to cli. This cli gets encoded into `state` of the oauth2 redirect and sent to the server's auth url (/auth/cli).
Server then calls discord api to get user data, and inserts it into the database table, mapping the cli_id to the user_id.
To ban a user, we just ban based on discord username/user_id, this then doesn't allow them to auth via cli either. (NOT IMPLEMENTED YET)
This will then need a followup pr making each route also accept cli_id in the params.
Also possible update is to only use global discord names for the leaderboard, we should unify that (will tackle in another PR as well)
Makes heavy use of …
=> Feat: Authenticate from CLI

src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/report.py
Leaderboard runs currently don't show up in the generated report, so if something goes wrong, there is no info.
=> include leaderboard results in report

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/report.py
Move all (direct) interactions with discord into the `Reporter` object. `submit_leaderboard` no longer takes an `interaction` parameter.
This is built on top of #229
=> Refactoring pt. 2

docker/amd-docker.Dockerfile
Update amd docker to rocm 6.3.1
```bash
```
```
```
README.md.
=> Update amd docker to latest deps.

src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/leaderboard_db.py
Reenables authentication for users via CLI
=> Feat: reenable validation

docker/amd-docker.Dockerfile
Add full rocm to add support for deps like rocThrust to support hip inline.
```bash
```
```
```
README.md.
=> Add all of rocm.

src/discord-cluster-manager/cogs/leaderboard_cog.py
We'll need to distinguish between inline and non-inline hip at some point, but for now, this unblocks us
=> enable comments in HIP template

src/discord-cluster-manager/launchers/github.py
```bash
```
```
```
README.md.
=> Feat: do not iterate on all runs

.github/workflows/amd_workflow.yml, docker/amd-docker.Dockerfile
This commit removes the python setup step from the workflow in every run, and we move it to the docker instead. This brings startup times to < 3 seconds, and it also allows us to install aiter (hash: 1d88633958236e942cba3c283864282f7af3ebc5) cleanly as it is a `python setup.py` install which installs on the docker's installed python so we now use it in the job instead of relying on the github python setup.
Tested here: https://github.com/gpu-mode/discord-cluster-manager/actions/runs/14635638085
```bash
```
```
``` …
=> Add aiter install to amd docker.

src/discord-cluster-manager/run_eval.py
```bash
```
```
```
README.md.
=> Fix: make run_config respect timeout specifications

src/discord-cluster-manager/launchers/github.py
```bash
```
```
```
README.md.
=> Fix: make gh timeout longer

src/discord-cluster-manager/launchers/github.py
```bash
```
```
```
README.md.
=> Feat: fix gh finding old runs

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/report.py
Remove the code bloacks that automatically create "active-leaderboards" channels
- ❌ (Don't have access to runners) Run the slash command `/verifyruns` on your own server.
```bash
```
```
```
README.md.
=> Remove automatic creation of active-leaderboards channels

src/discord-cluster-manager/cogs/leaderboard_cog.py
Adds `/leaderboard help` which gives a summary of the commands and links to the documentation.
- ❌ (skipped) Run the slash command `/verifyruns` on your own server.
```bash
```
```
```
README.md.
=> Add help command linking to docs

src/discord-cluster-manager/cogs/leaderboard_cog.py
Skip GPU selection prompt if only 1 possible GPU
Before:
(1 GPU available for leaderboard)
After:
(1 GPU available for leaderboard)
(multiple GPUs available for leaderboard)
- ❌ (skipped, don't have runners set up) Run the slash command `/verifyruns` on your own server.
```bash
```
```
```
README.md.
=> Skip GPU selection prompt if only 1 possible GPU

src/discord-cluster-manager/migrations/20250506_01_38PkG-add-index-on-runs-runner-score.py
This adds an index on the runs table to reduce the load time for the main page.
```bash
```
```
```
README.md.
=> Add index runs(runner, score)

.github/workflows/nvidia_workflow.yml, src/discord-cluster-manager/consts.py, src/discord-cluster-manager/launchers/github.py
This pr makes it such that we actually use the specified timeouts from github when running a submission. This logic was missing before. There's also a bunch of refactoring changes to make the linter happy.
Testing:
There is now a snippet in the logs that looks like 
```
2025-05-14 17:26:57 - utils - INFO - Waiting for workflow to complete... (timeout: 3 minutes)
2025-05-14 17:26:57 - utils - INFO - Workflow dispatch successful. Waiting 5s for the run to appear..
```
which indicates that we are passing a non default value. The associated workflow is https://github.com/gpu-mode/discord-cluster-manager/actions/runs/15033809006 (I believe the failure is noisy)
=> Fix Timeout Bug

src/discord-cluster-manager/api/main.py, src/discord-cluster-manager/api/utils.py, src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/misc_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/discord_reporter.py, src/discord-cluster-manager/discord_utils.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/report.py, src/discord-cluster-manager/submission.py, src/discord-cluster-manager/task.py, src/discord-cluster-manager/ui/misc.py, src/discord-cluster-manager/utils.py
In preparation for further cleanups, this PR tries to disentangle our files so there is less (direct and indirect) importing of discord happening.
* db is not independent from env
* db helper typedefs are now in db file (not 100% sure about that one, but imo a better place than "utils")
* instead of a global, the db stores the LRU cache as a member
* moved all utilities that interact with discord into a separate file
This should lay the groundwork so that we can make a libkernelbot python package that is completely independent from discord, and gets imported by the bot. Once we have this, we can start moving more functionality into this lib (looking at you, `reports.py`)
The PR contains a bunch of changes, but each individual commit should be fairly straightforward.
=> Disentangling discord

src/discord-cluster-manager/api/main.py, src/discord-cluster-manager/api/utils.py, src/discord-cluster-manager/backend.py, src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/discord_reporter.py, src/discord-cluster-manager/report.py, src/discord-cluster-manager/submission.py
This moves the remaining critical bits of submission logic out of SubmitCog, which now only exists to submit the legacy  "run" commands; don't think we've ever used them, maybe just nuke them to get rid of the complexity?
There are still lots of submission-related things scattered and duplicated all across the codebase, but if i didn't miss anything, this should make it possible to write a new/additional main file that enables running the API without the discord bot being required.
=> add a backend class that handles db and submission triggering

src/discord-cluster-manager/api/api_utils.py, src/discord-cluster-manager/api/main.py
=> Fix: correct db access

.github/workflows/runner_ci.yml, src/libkernelbot/submission.py, src/libkernelbot/task.py, src/libkernelbot/utils.py, unit-tests/test_report.py, unit-tests/test_submission.py, unit-tests/test_task.py, unit-tests/test_utils.py
This PR adds a bunch of unit tests for libkernelbot. While doing so, slight improvements (error checking) were made to submission.py.
This doesn't cover all the files in libkernelbot, but `consts.py` and `db_types.py` just define dataclasses/enums so there's not much to test there, and `leaderboard_db.py`, `backend.py` how much **unit** testing we can actually do there (i.e., is it even worth trying to mock the db, or should we just aim for some integration tests that actually start the postgres service and populate a real database?)
The tests for report.py are mostly claude generated, with some strong opinionated guidance to make them somewhat manageable.
=> Adding unit tests

docker-compose.test.yml, pyproject.toml, src/libkernelbot/leaderboard_db.py, src/migrations/20250728_01_Q3jso-fix-code-table.py, unit-tests/test_leaderboard_db.py
Uses docker-compose to start up a container with the db, and  run the yoyo migrations, so we can access a real database for our testing.
All of this is wrapped inside a pytest fixture, so for local testing you can just run pytest as normally. However, this means that pytest now takes a few seconds to start up, because it waits on the docker container being available.
While developing this, I've fixed a few minor and a major problem. Please take a **careful** look at the migration here, and check if it makes sense to you. 
Apart from the code file fix, this fixes a sign error when getting leaderboard names (for autocomple) and does some small cleanups/error handling improvements.
The code paths where the database returns an error are currently ignored in coverage reporting; while for some …
=> Database tests

src/libkernelbot/launchers/github.py
We sometimes still happen to end up with `could not find a job with name ....` when running GH runs, might be that the sleep is too tight for github api to propagate the changes, idk.
=> Increase wait time to 10

.github/workflows/amd_workflow.yml, .github/workflows/nvidia_workflow.yml, scripts/ci_test_cuda.py, scripts/ci_test_python.py, src/kernelbot/discord_reporter.py, src/libkernelbot/launchers/github.py, src/libkernelbot/report.py, src/libkernelbot/run_eval.py, tests/test_backend.py, tests/test_report.py
This PR adds some infrastructure for dealing with profiling data. Basically, the idea is that any data which is placed in the `profile_data/` directory in the github runner is exported (when `EvalResult.profile_result` is set) to the user via discord. As discord attachments could not handle the size of download artifacts (typically up to ~35 MB), I've opted to simply present a direct link to the GitHub artifact. To this end, I've modified the GH launcher to provide a sort of 'index' of artifacts, which can then either be downloaded by the bot or presented as download link.
I've also fixed some minor bugs in `run_eval.py` related to fetching ROCm system info, as well as added some extra info to `SystemInfo` about the runtime (useful elsewhere in the evaluating process when the actual …
=> Profiling Infrastructure

src/libkernelbot/run_eval.py
This is an initial implementation of profiling using rocPROF for MI300 jobs. It works as follows: When the profiling run time is selected, the application is simply executed using rocPROF with options set to gather a bunch of traces. These are then packages with RunResults, and finally sent to the user. This current version is the most straight forward way to implement this, but there are some missing features and limitations:
- A github link is now shared
- I think its best to leave this out
=> Initial AMD Profiling

docker/amd-docker.Dockerfile
Add https://github.com/ROCm/iris install to amd dockerfile.
```bash
```
```
```
README.md.
=> Add iris install.

src/kernelbot/cogs/admin_cog.py
This is a temporary fix jsut so I can deploy the problem, we should probably remove the functionality to create threads anyway as they aren't particularly used.
=> Temporary fix, send only split log
