discord-bot.py
A small improvement, resulting in less manual work when testing the bot locally. Automatically detects the remote branch via subprocess call to be used in the workflow dispatch.
=> Feat: add auto detection of github remote branch, fallback to main

.github/workflows/train_workflow.yml, train.py
=> Add torch AMD GPU runners

.github/workflows/train_workflow.yml, train.py
Install numpy / Triton / torch based on grepping the train.py. If it's too slow, we can change this in the future.
=> Add Numpy / Torch / Triton differentiation

.github/workflows/train_workflow.yml, train.py
Reverts gpu-mode/discord-cluster-manager#18
=> Revert "Add Numpy / Torch / Triton differentiation"

README.md, discord-bot.py, modal_runner.py, requirements.txt
Still has an annoying bug where modal is trying to run the bot code itself instead of the train.py
Logging statements though show that the filename and contents are correct
And I know a toy example like the one in https://github.com/gpu-mode/discord-cluster-manager/blob/main/scripts/modal-test.py works fine
=> modal branch

.gitignore, README.md, discord-bot.py
Making some more UX changes please dont merge yet
Video demo here https://discord.com/channels/1303055581078093874/1303055581078093877/1308510238999052380
Added a few commands
* `resync` which will remove all custom commands
* `ping` which is just a health checker for the bot - it should reply with `pong`
* `run github` which is the first main subcommand which will launch a github action and either take AMD or NVIDIA as an argument which decides which workflow file to run
* `run modal` will launch a command on modal, our favorite choice for python jobs and takes in as argument a gpu type which does nothing right now
Also some random refactoring
=> slash commands now work

modal_runner.py
5 min timeout so folks don't bankrupt me
=> add timeout for modal

src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/modal_runner.py
Enables running a CUDA script on Modal provider, when provided with file that ends with `.cu`
=> Feat: support cuda on modal

README.md
After I went through the documentation setup steps myself, I saw on Discord that S1ro mentioned they wanted to add images. 
So I just went ahead and added images that would've made the process easier. 
🤗
=> Update README.md with images

.ruff.toml, src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/leaderboard_db.py
This change reduces the line length to 100.
```bash
```
```
```
README.md.
=> reduce line length to 100

README.md
Update the diagram in the README with the correct bot permissions.
```bash
```
```
```
README.md.
=> Update README.md with correct Bot Permissions

src/discord-cluster-manager/cogs/leaderboard_cog.py
This is just a UI change. The `/leaderboard submit github` runner will just always send to the NVIDIA gpus, but we will have to change this later when the schema and autocorrect are added.
```bash
```
```
```
README.md.
=> Remove gpu_type from GH submit and add same UI as create for /leaderboard submit.

README.md
Reordered + added a few instructions to ensure future contributors do not run into walls I recently experienced.
Mainly: 
- notes regarding directly cloning (and not forking), Python version, required GitHub token permissions with visual. 
Also, I think my auto-formatter on VSCode reformatted a bunch of lines so it inflated the LOC but oh well. 
```bash
```
```
```
For more …
=> Smol README changes for (imo) easier setup

README.md, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_eval.py
@S1ro1 Update reference code and README to be generic.
```bash
```
```
```
README.md.
=> Update Python Reference code / docs to match CUDA

src/discord-cluster-manager/modal_runner.py
```bash
```
```
```
README.md.
=> Fix: add deps and fix torch modal

src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/modal_runner.py
Some Minor fixes.
```bash
```
```
```
README.md.
=> Fix: minor post-launch tweaks

examples/simple_cuda/reference.cu, examples/simple_cuda/submission.cu, examples/softmax_py/reference.py, examples/softmax_py/submission.py, examples/thunderkittens_example/reference.cu, examples/thunderkittens_example/submission.cu, src/discord-cluster-manager/cogs/leaderboard_cog.py
Examples of CUDA, Python, and TK leaderboards. Feel free to add more!
```bash
```
```
```
README.md.
=> Example Kernels for the Leaderboard 

.github/workflows/deploy-docs.yml, .gitignore, docs/docs/submitting-your-first-kernel/cuda-submissions.md, docs/docs/submitting-your-first-kernel/python-submissions.md, docs/package.json, docs/src/pages/markdown-page.md, docs/yarn.lock
```bash
```
```
```
README.md.
=> Fix the GitHub Pages Loader

docs/docusaurus.config.ts, docs/src/pages/index.tsx
```bash
```
```
```
README.md.
=> Doc updates

README.md
```bash
```
```
```
README.md.
=> Add /leaderboard show-personal to README.md

src/discord-cluster-manager/consts.py
Fixes a minor typo making github submission silently crash.
```bash
```
```
```
README.md.
=> Fix: make gpu selection respect the runner name capitalization

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/submit_cog.py
Each commit here is a mostly independent fix or usability improvement. I didn't want to create a whole bunch of PRs for this, but if there is any non-trivial problem here, I'd just separate that commit out into its own PR.
Mostly small code cleanups, but also some small usability improvements:
1) leaderboard creation checks that deadline is not in the past
2) if a leaderboard allows exactly one GPU, the GPU selection popup is avoided (really nice for debugging)
=> Small fixes and improvements

src/discord-cluster-manager/cogs/leaderboard_cog.py
As this is supposed to be the super convenient development option, make it as quick as possible: Infer leaderboard name from directory, and allow setting the GPU directly from the command interface.
=> more convenient create local

src/discord-cluster-manager/cogs/leaderboard_cog.py
actually use the task description.
=> use task description for forum message

examples/identity_cuda/submission.cu, examples/identity_cuda/task.yml, examples/identity_cuda/template.cu, examples/identity_py/submission.py, examples/identity_py/task.yml, examples/identity_py/template.py, examples/matmul_py/submission.py, examples/matmul_py/task.yml, examples/softmax_py/submission.py, examples/softmax_py/task.py, examples/softmax_py/task.yml, examples/template.cu, examples/template.py, examples/thunderkittens_example/submission.cu, examples/vectoradd_py/submission_cuda_inline.py, examples/vectoradd_py/submission_triton.py, examples/vectoradd_py/task.py, examples/vectoradd_py/task.yml, examples/vectoradd_py/template-triton.py, examples/vectoradd_py/template.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/consts.py, src/discord-cluster-manager/task.py
* infer runner(s) from selected GPU(s)
* allow selecting GPU directly from command
* allow selecting  GPU and leaderboard with comment in submission file
* starter template files for participants to download
=> Command improvements

src/discord-cluster-manager/api/main.py, src/discord-cluster-manager/bot.py
=> add very simple limits to API endpoints

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py
Create an AdminCog and move our admin commands there.
Adds a command to enable/disable the bot from accepting new submissions.
Also, I spent a few minutes wondering why the bot wasn't working, only to realize the DB service wasn't running. Now the bot will refuse to start in such circumstances, giving a clear error message.
=> admin commands

src/discord-cluster-manager/api/main.py
Api broke with some previous PR, fix that.
```bash
```
```
```
README.md.
=> Fix: fix api calls to conform to new gpu_lookup

requirements.txt
Probably a last part of the small fixes to make fastapi work
```bash
```
```
```
README.md.
=> Fix: requirements

src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/env.py, src/discord-cluster-manager/leaderboard_db.py
Fetch tasks from a dedicated repository.
Barely functional at this point, but enough to hopefully illustrate what I'm aiming for.
=> Problems Repo

examples/eval.py, src/discord-cluster-manager/cogs/verify_run_cog.py
db raises, don't try to validate the return value
=> fix verify_task

src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/report.py
bugfix, plus try-except block that makes issues like this easier to debug in the future
=> better error reporting and bugfix

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/report.py
=> more bugfixes

src/discord-cluster-manager/report.py, src/discord-cluster-manager/utils.py
=> bugfix collection

.github/workflows/lint.yml, .github/workflows/modal-deploy.yml, .github/workflows/runner_ci.yml
=> Add dev environment to github branch

scripts/update_leaderboard.py
Fixes the website after the DB schema changed. A bit jank.
```bash
```
```
```
README.md.
=> Fix Website Leaderboard after DB changes (#171)

src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/utils.py
Contains also some smaller other fixes/improvements
=> Allow querying past submissions

src/discord-cluster-manager/leaderboard_db.py
Only shows top submissions per user in case of generic `show`, shows all for personal.
Code just splits it into 2 paths for better readability
```bash
```
```
```
README.md.
=> Feat: only query top user submission for show

Aptfile, Procfile, src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/misc_cog.py, src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/cogs/verify_run_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/utils.py
We're ready 🚀 
```bash
```
```
```
README.md.
=> Last one before launch 🫡 

src/discord-cluster-manager/cogs/admin_cog.py
Fix
```bash
```
```
```
README.md.
=> Fix: wrong problem dir

docs/docs/active.md
```bash
```
```
```
README.md.
=> Add Updated LB descriptions to the docs.

src/discord-cluster-manager/run_eval.py
* fix setting correct end_time for python jobs
* add a "compile" step to python to pre-populate `load_inline` cache
=> Timeout related fixes

src/discord-cluster-manager/modal_runner.py
Small PR, adds tinygrad as first class citizen so no need to `pip install` inside script to get it.
```bash
```
```
```
README.md.
=> Feat: add tinygrad

docs/src/pages/index.module.css, docs/src/pages/index.tsx, scripts/update_leaderboard.py
Update the website to be less 1990s. Example below:
```bash
```
```
```
README.md.
=> Update Leaderboard UI / Website to show Rankings

docs/src/pages/index.module.css, docs/src/pages/index.tsx, scripts/update_leaderboard.py
Leaderboards used to rank all submissions for every user, now only shows the top submission per LB (per device).
```bash
```
```
```
README.md.
=> Leaderboard only shows one submission per user.

.github/workflows/deploy-docs.yml
Update the website every 10 min. instead of every day -- it's a very light load and it'll help people enjoy looking at rankings more.
```bash
```
```
```
README.md.
=> Schedule deploy-docs every 10 min. instead of every day.

.github/workflows/deploy-docs.yml
The previous syntax was wrong it seems, it still did every day (can someone double check this for me).
```bash
```
```
```
README.md.
=> LB updates every 10 minutes

requirements.txt, src/discord-cluster-manager/cogs/submit_cog.py
Very fast
```
ao ❯ time python -c "from better_profanity import profanity; print(profanity.contains_profanity('sex'))"
True
python -c   0.02s user 0.01s system 37% cpu 0.092 total
~/Dev/discord/discord-cluster-manager msaroufim/profanity*
ao ❯ 
```
And quite sophisticated https://github.com/snguyenthanh/better_profanity
The main con is it's 4 years old
=> Better profanity

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/report.py, src/discord-cluster-manager/utils.py
* make error messages ephemeral
* better formatting of times (should we call theses scores, and then report in ms?)
* consolidate private run  result report into a single discord message
=> Collection of small improvements

scripts/update_leaderboard.py, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/ui/misc.py
Adds an admin command to delete a submission of a given ID, taking care to delete the corresponding runs first.
=> WIP: admin delete submission

scripts/update_leaderboard.py, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/report.py, src/discord-cluster-manager/ui/misc.py, src/discord-cluster-manager/utils.py
* admin delete submission
* Fix Decimal conversion, lint errors
---------
Co-authored-by: Alex Zhang <alex.lx.zhang@gmail.com>## Description
```bash
```
```
```
README.md.
=> [WIP] Merge Dev to Main March 8

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py
Actually makes the user names stored in db #200 
```bash
```
```
```
README.md.
=> Feat: add user names to submission

src/discord-cluster-manager/cogs/github_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/migrations/20250304_01_DzORz-collect-system-information-for-each-run.py, src/discord-cluster-manager/modal_runner.py, src/discord-cluster-manager/run_eval.py, src/discord-cluster-manager/ui/misc.py, src/discord-cluster-manager/utils.py
An attempt to record more information about the system we're running on. If we'd done that from the beginning, we would've been able to identify the submissions that were affected by our unspecific modal runner selection.
This implementation imports pytorch to get the GPU name from python, which would be required now even for pure cuda submissions.
=> Record system information

src/discord-cluster-manager/modal_runner.py
Fixes the automount warnings we  started getting recently.
=> fix some modal deprecation warnings

.gitignore, src/discord-cluster-manager/consts.py, src/discord-cluster-manager/http_runner.py, src/discord-cluster-manager/modal_runner.py, src/discord-cluster-manager/modal_runner_archs.py
```bash
```
```
```
README.md.
=> Use B200s (temporarily) for Leaderboard

src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/utils.py
Achievement-type messages after successful leaderboard submission
=> post submission summary message with celebrations

src/discord-cluster-manager/cogs/modal_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/report.py
Less ambitious version of #219 
Minor improvements to our run messages:
reduce the number of total messages, more info, started splitting the monstrosity that is `generate_report`
=> Submission message update

src/discord-cluster-manager/cogs/leaderboard_cog.py
For personal submissions, we don't need to show the user column, so we get a bit more space for useful stuff.
This enables showing the submission's id and when it was submitted. In order to fit in the width limit, _either_ the date _or_ the time can be shown. So for recent (<24h) submissions, we show the time, for older submissions, the date. 
I think we currently just show the time in the timezone the bot is running in? Should we try to adjust this to the users timezone?
=> personal submissions now show submission id and submission date

src/discord-cluster-manager/cogs/submit_cog.py
=> add user to private thread

src/discord-cluster-manager/utils.py
Specifically intercept uncaught KernelBotError messages and print a useful message.
=> KernelBotError error message

examples/eval.py, examples/identity_py/task.yml, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/consts.py, src/discord-cluster-manager/run_eval.py, src/discord-cluster-manager/task.py, src/discord-cluster-manager/utils.py
Allow specifying a ranking criterion in task.yml. Currently implements `last` (only last benchmark counts), `mean` (arithmetic mean) and `geom` (geometric mean).
=> Geomean ranking

src/discord-cluster-manager/leaderboard_db.py
```bash
```
```
```
README.md.
=> Fix: enable invalidated submissions

src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/leaderboard_db.py
```bash
```
```
```
README.md.
=> Fix: remove schedule cleanup

docker-compose.yml, src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/cogs/submit_cog.py, src/discord-cluster-manager/launchers/github.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/report.py, src/discord-cluster-manager/utils.py
=> Post-launch fixes

src/discord-cluster-manager/cogs/admin_cog.py
=> allow force-updating a LB

src/discord-cluster-manager/report.py
Will be helpful to debug precision-related problems
=> allow printing messages for passed tests

src/discord-cluster-manager/api/main.py
WIP: have to recheck when I have fresh mind, but should avoid the timeouts from heroku by utilizing streaming responses.
=> Feat: streaming response

src/discord-cluster-manager/launchers/github.py
```bash
```
```
```
README.md.
=> Feat: more logging

src/discord-cluster-manager/consts.py, src/discord-cluster-manager/task.py
```bash
```
```
```
README.md.
=> Feat: fix timeouts for now

src/discord-cluster-manager/cogs/admin_cog.py
```bash
```
```
```
README.md.
=> Fix: another possible error

docker/amd-docker.Dockerfile
This PR resolves github runner aiter perms.
```bash
```
```
```
README.md.
=> Resolve AITER github runner perms.

src/discord-cluster-manager/cogs/admin_cog.py, src/discord-cluster-manager/leaderboard_db.py, src/discord-cluster-manager/report.py
Add a few more stats to the stats command:
* Make two versions, one overall and one for last day
* calculate the total running time, as well as the average and maximum time between submission and start of a run
=> Extended stats

src/discord-cluster-manager/api/main.py, src/discord-cluster-manager/api/utils.py
Updates to our result reporting:
* include status and id of run in thread name
* allow passing reports through to the API
* include interpretation of exit code in short reports
* detailed report can be generated without reference to discord thread
=> WIP: More reporting

.github/workflows/runner.py, src/discord-cluster-manager/bot.py, src/discord-cluster-manager/cogs/leaderboard_cog.py, src/discord-cluster-manager/env.py, src/discord-cluster-manager/launchers/github.py, src/discord-cluster-manager/leaderboard_db.py
Avoid running into gh size limits (or at least push them to larger inputs).
In the process of debugging/testing this, I think I've also identified (and fixed) the backslash problem.
=> compress github action payload

src/discord-cluster-manager/modal_runner.py, src/discord-cluster-manager/modal_runner_archs.py
An attempt to provide fixed versions and update our dependencies. I tried to include a few more of the nvidia python libraries, but it's a mess (e.g., `nvmath-python'  conflicts with 'cuda-core`); probably cutlass-dsl is the most important one, though, which seems to work.
=> update and pin modal images

src/discord-cluster-manager/discord_utils.py, src/discord-cluster-manager/leaderboard_db.py
=> filter for active leaderboards

examples/eval.py, examples/utils.py, src/libkernelbot/backend.py, src/libkernelbot/db_types.py, src/libkernelbot/leaderboard_db.py, src/libkernelbot/submission.py
A bunch of changes I made when looking into milestones, but which are independent of the actual milestone implementation.
=> Smaller refactorings

.github/workflows/coverage.yml, .github/workflows/runner_ci.yml, .github/workflows/unit_tests.yml, pyproject.toml, src/libkernelbot/report.py, src/libkernelbot/submission.py, src/libkernelbot/task.py, unit-tests/test_report.py, unit-tests/test_submission.py, unit-tests/test_task.py, unit-tests/test_utils.py
Enables generation of coverage reports and extends some testing so that the targeted files get >90% coverage.
=> enable coverage reports

.github/workflows/coverage.yml
```bash
```
```
```
README.md.
=> Update token for codecov.yml

README.md, src/kernelbot/cogs/admin_cog.py, src/kernelbot/cogs/verify_run_cog.py
Some fixes and amendments to things that I ran into during setting up the development environment,
- ^ Can't do this because its broken rn
=> Some setup fixes

src/libkernelbot/consts.py, src/libkernelbot/launchers/github.py, src/libkernelbot/task.py
=> Feat: add mi300x8

docker/amd-docker.Dockerfile
Testing rocshmem.
```bash
```
```
```
README.md.
=> rocshmem dependencies

examples/eval.py
This PR adds profiling info gathering to the example `eval.py`. The following things are added:
* Profiling implemented for distributed runs in general
* Currently, each process gathers results via `torch.profiler.profile` as with the single-threaded case. The resulting events are passed to the main process, where they are averaged over all processed. Unfortunately `torch.profiler` does not have this functionality by default, so I just looked up the way that they do it and then replicated it here. This is all user-facing API, so I don't think there should be a problem, though I don't know how reliable pytorch is with this stuff in general
* NVTX markers are also emitted for the different sections like nccl init/generate input/executing kernel. These emit rocTX markers under ROCm, so this …
=> examples: profiling
